### ISSUE TITLE
剪切完成后保存，通过合成器Muxer，在输出渲染时，无法执行drawFrame

### ISSUE THREAD

**Issue by BlackMonkeyidea** [TryLoveCatch/videoEditor#1]
在最后视频渲染时，某一次drawFrame执行到清除当前深度缓冲区和颜色缓冲区，无法执行下去，无法完成视频合成，请问作者大大有没有遇到过这样的问题，可否分享下，不胜感激
        
        GLHelper.checkGlError(TAG, "onDrawFrame start");
        //GLES兼容转换矩阵，用于图像的旋转和翻转不能用于裁剪
        st.getTransformMatrix(mSTMatrix);

        //清空当前所有颜色
        GLES20.glClearColor(0.0f, 1.0f, 0.0f, 1.0f);
        //清空当前深度缓冲区和颜色缓冲区
        GLES20.glClear(GLES20.GL_DEPTH_BUFFER_BIT | GLES20.GL_COLOR_BUFFER_BIT);
        
        GLES20.glUseProgram(program);//使用这个程序
        GLHelper.checkGlError(TAG, "glUseProgram");

**Comment by TryLoveCatch** [comment]
不好意思，我没有遇到过，我这个是临时的调研任务，只有参考价值，具体的还得你自己研究来
